# Config version, used for tracking configuration changes and updates.
config-version: 3

# The primary framework the plugin operates under. Supports "towny" for integration with Towny.
framework: towny

# List of valid government types that can be set within the plugin.
validGovernmentTypes:
  - DEMOCRACY
  - DICTATORSHIP

# Toggle for enabling or disabling government functionalities.
govEnabled: true

# Toggle for enabling or disabling organization functionalities.
orgEnabled: true

# Toggle for enabling or disabling army functionalities.
armyEnabled: true

# Cost for visiting a nation with a diplomatic status of neutral or none.
diplomacyVisitCostNeutralNone: 1000.00

# Cost for visiting a nation with a friendly diplomatic status.
diplomacyVisitCostFriendly: 750.00

# Cost to form a trade agreement between two nations.
diplomacyFormCostTrade: 10000.00

# Cost to form an organization.
orgFormationCost: 25000.00

# Whether the business organization functionality is locked to towns only.
orgBusinessTownLocked: false

# Limit of organizations a resident can be part of. Set to -1 for no limit.
residentOrgLimit: -1

# Language (en = English) // Locale support is planned for a future release.
locale: en
